import copy
import math
import os
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Optional
from lib import utils


import glog
import torch

from lib.linear.ec_linear import EntropyConstrainedLinear as _ECLinearCompressAI
from lib.linear.ec_linear_parametric import EntropyConstrainedLinear as _ECLinearParametric
from lib.linear.ec_linear_lattice_eb import EntropyConstrainedLinear as _ECLinearLatticeEB
from lib.algo import ecsq

EntropyConstrainedLinear = _ECLinearCompressAI  # default for type hints


def _layer_variant(layer) -> str:
    mod = type(layer).__module__
    if "lattice_eb" in mod:
        return "lattice_eb"
    if "parametric" in mod:
        return "parametric"
    return "compressai"


def load_pretrained_ec_state(layer, pretrained_path: str, strict_variant: bool = True) -> None:
    """Load `qs` / `entropy_bottleneck` / (lattice_eb only) `B` from a
    pretrained-on-Gaussian checkpoint (produced by `pretrain_ec_gaussian.py`)
    into an already-constructed EntropyConstrainedLinear.
    Does NOT touch latent / left_diag / right_diag — those are per-layer."""
    pt = torch.load(pretrained_path, map_location="cpu", weights_only=False)
    expected_variant = str(pt.get("variant", "compressai"))
    actual_variant = _layer_variant(layer)

    if strict_variant and expected_variant != actual_variant:
        raise ValueError(
            f"Pretrained variant '{expected_variant}' does not match layer "
            f"variant '{actual_variant}'. Rebuild the pretraining with the "
            f"matching --variant, or set strict_variant=False."
        )

    dev = layer.latent.device
    dtype = layer.latent.dtype

    # qs
    if "qs" in pt and pt["qs"] is not None:
        layer.qs = pt["qs"].to(device=dev, dtype=torch.float32).reshape(())

    # entropy bottleneck — drop CDF-table buffers (they'll be regenerated by
    # update_entropy_model below once medians/quantiles are loaded).
    eb_state_cpu = pt.get("entropy_bottleneck")
    if eb_state_cpu is not None:
        eb_state = {
            k: v.to(device=dev, dtype=torch.float32)
            for k, v in eb_state_cpu.items()
            if k not in ("_offset", "_quantized_cdf", "_cdf_length")
        }
        missing, unexpected = layer.entropy_bottleneck.load_state_dict(eb_state, strict=False)
        if unexpected:
            glog.warning(f"[ec pretrained] EB load unexpected keys: {list(unexpected)}")
        # Rebuild CDF tables from the loaded medians/quantiles
        layer.update_entropy_model(force=True, update_quantiles=False)

    # B (lattice_eb only)
    if actual_variant == "lattice_eb":
        if "B" not in pt:
            raise ValueError("lattice_eb layer but checkpoint has no B tensor")
        B_pt = pt["B"]
        if tuple(layer.B.shape) != tuple(B_pt.shape):
            raise ValueError(
                f"B shape mismatch: layer={tuple(layer.B.shape)} vs "
                f"pretrained={tuple(B_pt.shape)} — did you use matching --lattice_dim?"
            )
        layer.B.data.copy_(B_pt.to(device=dev, dtype=dtype))


def _build_ec_layer(args, in_features: int, out_features: int, decoder_type: str, rht_seed: Optional[int], device, dtype):
    """Factory: pick compressai, parametric, or lattice_eb EntropyConstrainedLinear based on args."""
    entropy_model = str(getattr(args, "ecft_entropy_model", "compressai")).lower()
    chunk_rows = int(getattr(args, "ec_entropy_chunk_rows", 0) or 0)

    if entropy_model == "parametric":
        num_g = int(getattr(args, "ecft_num_gaussian", 3))
        num_l = int(getattr(args, "ecft_num_laplacian", 3))
        layer = _ECLinearParametric(
            in_features=in_features,
            out_features=out_features,
            bias=False,
            decoder_type=decoder_type,
            entropy_bottleneck_kwargs={"num_gaussian": num_g, "num_laplacian": num_l},
            rht_seed=rht_seed,
            device=device,
            dtype=dtype,
        )
        if chunk_rows > 0:
            layer.entropy_chunk_rows = chunk_rows
        return layer
    if entropy_model == "lattice_eb":
        lattice_dim = int(getattr(args, "ecft_lattice_dim", 4))
        lambda_ortho = float(getattr(args, "ecft_lambda_ortho", 0.0) or 0.0)
        B_init = str(getattr(args, "ecft_B_init", "identity"))
        B_init_scale = getattr(args, "ecft_B_init_scale", None)
        B_init_scale = float(B_init_scale) if B_init_scale is not None else None
        layer = _ECLinearLatticeEB(
            in_features=in_features,
            out_features=out_features,
            bias=False,
            decoder_type=decoder_type,
            lattice_dim=lattice_dim,
            lambda_ortho=lambda_ortho,
            B_init=B_init,
            B_init_scale=B_init_scale,
            rht_seed=rht_seed,
            device=device,
            dtype=dtype,
        )
        if chunk_rows > 0:
            layer.entropy_chunk_rows = chunk_rows
        return layer
    if entropy_model == "compressai":
        return _ECLinearCompressAI(
            in_features=in_features,
            out_features=out_features,
            bias=False,
            decoder_type=decoder_type,
            rht_seed=rht_seed,
            device=device,
            dtype=dtype,
        )
    raise ValueError(
        f"--ecft_entropy_model must be 'compressai', 'parametric', or 'lattice_eb', got {entropy_model!r}"
    )


def _maybe_apply_pretrained(layer, args) -> bool:
    """If args.ec_pretrained_path is set, load the checkpoint into `layer`.
    Returns True if a pretrained state was applied."""
    path = getattr(args, "ec_pretrained_path", None)
    if not path:
        return False
    load_pretrained_ec_state(layer, path)
    glog.info(f"[ec pretrained] loaded: {path}")
    return True


try:
    from NWC.utils.optimizers import configure_optimizers as configure_ec_optimizers
except ImportError:
    root = Path(__file__).resolve().parents[3]
    if str(root) not in sys.path:
        sys.path.append(str(root))
    from NWC.utils.optimizers import configure_optimizers as configure_ec_optimizers


def _to_optional_tensor(x: Optional[Any], length: int, device: torch.device, dtype: torch.dtype) -> Optional[torch.Tensor]:
    if x is None:
        return None
    if torch.is_tensor(x):
        t = x.to(device=device, dtype=dtype)
    else:
        t = torch.as_tensor(x, device=device, dtype=dtype)
    if t.ndim == 2 and t.shape == (1, length):
        t = t[0]
    if t.ndim == 2 and t.shape == (length, 1):
        t = t[:, 0]
    if t.ndim != 1 or t.numel() != length:
        raise ValueError(f"Expected 1D tensor with {length} elements, got {tuple(t.shape)}")
    return t


def _resolve_decoder_type(args) -> str:
    for key in ("ec_decoder_type", "decoder_type", "ecft_decoder_type"):
        value = getattr(args, key, None)
        if value is not None:
            return value
    return "rht"


def _resolve_rht_seed(args) -> Optional[int]:
    for key in ("ec_rht_seed", "rht_seed", "ecft_rht_seed"):
        if hasattr(args, key):
            return getattr(args, key)
    return 0

def _build_optimizer_args(args):
    return SimpleNamespace(
        learning_rate=float(getattr(args, "ecft_learning_rate", 1e-4)),
        aux_learning_rate=float(getattr(args, "ecft_aux_learning_rate", 1e-3)),
    )


def _rate_bits_per_param(likelihoods: torch.Tensor) -> torch.Tensor:
    return (-torch.log2(likelihoods.float().clamp_min(1e-9))).mean()


def _fuse_metadata_into_layer(
    layer: EntropyConstrainedLinear,
    metadata: dict[str, Any],
    args,
) -> bool:
    if not isinstance(metadata, dict):
        return False

    device = layer.latent.device
    dtype = layer.latent.dtype
    row_factor = torch.ones(layer.out_features, device=device, dtype=dtype)
    col_factor = torch.ones(layer.in_features, device=device, dtype=dtype)
    has_row = False
    has_col = False

    row_std = _to_optional_tensor(
        metadata.get("row_std"),
        layer.out_features,
        device,
        dtype,
    )
    if row_std is not None:
        if bool(getattr(args, "row_normalize2", False)):
            row_factor = row_factor * row_std
            has_row = True
        if bool(getattr(args, "row_normalize", False)) or bool(
            getattr(args, "normalization_search", False)
        ):
            row_factor = row_factor * row_std
            has_row = True

    col_std = _to_optional_tensor(
        metadata.get("col_std"),
        layer.in_features,
        device,
        dtype,
    )
    if col_std is not None and (
        bool(getattr(args, "col_normalize", False))
        or bool(getattr(args, "normalization_search", False))
    ):
        col_factor = col_factor * col_std
        has_col = True

    scale_h = _to_optional_tensor(
        metadata.get("scaleH"),
        layer.in_features,
        device,
        dtype,
    )
    if scale_h is not None:
        if bool(getattr(args, "scaleHinv", False)):
            col_factor = col_factor / scale_h
            has_col = True
        if bool(getattr(args, "scaleH", False)):
            col_factor = col_factor / scale_h
            has_col = True

    if not has_row and not has_col:
        return False

    layer.fuse_decoder_diagonal(
        row_scale=row_factor if has_row else None,
        col_scale=col_factor if has_col else None,
        inverse=False,
    )
    return True


def _search_qs_for_target_rate(
    layer: EntropyConstrainedLinear,
    args,
    device: torch.device,
    dtype: torch.dtype,
    log_path: Optional[str] = None,
) -> Optional[torch.Tensor]:
    target_rate = getattr(args, "R_target", None)
    if target_rate is None:
        return None

    best_qs, theory_rate, ecsq_mse = ecsq.binary_search_qs(
        layer.latent.detach(), target_rate=float(target_rate)
    )
    qs_tensor = torch.tensor(float(best_qs), device=device, dtype=dtype)
    layer.qs = qs_tensor
    if bool(getattr(args, "verbose", False)):
        glog.info(
            "[ECFT qs-search] "
            f"R_target={float(target_rate):.6f} "
            f"qs={float(best_qs):.6f} "
            f"theory_rate={float(theory_rate):.6f} "
            f"ecsq_mse={float(ecsq_mse):.6f}"
        )
    _ecft_log_append_qs_search(
        log_path,
        target_rate=float(target_rate),
        qs=float(best_qs),
        theory_rate=float(theory_rate),
        ecsq_mse=float(ecsq_mse),
    )
    return qs_tensor


def _clone_best_state(model: EntropyConstrainedLinear) -> dict[str, torch.Tensor]:
    state = {}
    for name, tensor in model.state_dict().items():
        state[name] = tensor.detach().cpu().clone()
    return state


def _ecft_log_path(args) -> Optional[str]:
    save_root = getattr(args, "res_path", None) or getattr(args, "save_path", None)
    if not save_root:
        return None
    layer_idx = getattr(args, "layer_idx", None)
    layer_name = getattr(args, "layer_name", None)
    if layer_idx is None or layer_name is None:
        return None
    log_dir = os.path.join(save_root, "ecft_log")
    os.makedirs(log_dir, exist_ok=True)
    return os.path.join(log_dir, f"{layer_idx}_{layer_name}.log")


def _ecft_log_init(path: Optional[str], epochs: int, lmbda: float, decoder_type: str) -> None:
    if path is None:
        return
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            f"META epochs={epochs} lmbda={lmbda} decoder_type={decoder_type}\n"
        )
        f.write("STEP stage epoch loss mse_loss rate_loss aux_loss\n")


def _ecft_log_append_qs_search(
    path: Optional[str],
    target_rate: float,
    qs: float,
    theory_rate: float,
    ecsq_mse: float,
) -> None:
    if path is None:
        return
    with open(path, "a", encoding="utf-8") as f:
        f.write(
            "QS_SEARCH "
            f"R_target={target_rate:.8f} "
            f"qs={qs:.8f} "
            f"theory_rate={theory_rate:.8f} "
            f"ecsq_mse={ecsq_mse:.8f}\n"
        )


def _ecft_log_append_train(path: Optional[str], row: dict[str, float]) -> None:
    if path is None:
        return
    with open(path, "a", encoding="utf-8") as f:
        f.write(
            "STEP "
            f"{row['stage']} "
            f"{row['epoch']:.0f} "
            f"{row['loss']:.8f} "
            f"{row['mse_loss']:.8f} "
            f"{row['rate_loss']:.8f} "
            f"{row['aux_loss']:.8f}\n"
        )


def _ecft_log_append_final(
    path: Optional[str],
    mse_loss: float,
    rate_loss: float,
    bpp: float,
    decoder_bits_total: int,
) -> None:
    if path is None:
        return
    with open(path, "a", encoding="utf-8") as f:
        f.write(
            "FINAL "
            f"mse={mse_loss:.8f} "
            f"rate={rate_loss:.8f} "
            f"bpp={bpp:.8f} "
            f"decoder_bits_total={decoder_bits_total}\n"
        )


def _ecft_log_append_ecsq_compare(
    path: Optional[str],
    ecsq_compare: Any,
) -> None:
    if path is None:
        return
    with open(path, "a", encoding="utf-8") as f:
        f.write("ECSQ_COMPARE\n")
        if isinstance(ecsq_compare, dict) and ecsq_compare.get("ran", False):
            ec = ecsq_compare.get("ec", {})
            ecsq = ecsq_compare.get("ecsq", {})
            delta = ecsq_compare.get("delta", {})
            f.write(
                "ran=1 "
                f"target_rate={float(ecsq_compare.get('target_rate_from_ec', float('nan'))):.8f} "
                f"ec_mse={float(ec.get('mse', float('nan'))):.8f} "
                f"ec_rate={float(ec.get('rate_loss', float('nan'))):.8f} "
                f"ecsq_mse={float(ecsq.get('mse', float('nan'))):.8f} "
                f"ecsq_rate={float(ecsq.get('rate', float('nan'))):.8f} "
                f"delta_mse={float(delta.get('mse_ec_minus_ecsq', float('nan'))):.8f} "
                f"delta_rate={float(delta.get('rate_ec_minus_ecsq', float('nan'))):.8f}\n"
            )
            return
        if isinstance(ecsq_compare, dict):
            f.write(f"ran=0 reason={ecsq_compare.get('reason')}\n")
            return
        f.write(f"ran=- reason={ecsq_compare}\n")


# GLOBAL_STD = 0.012528747320175171

def ec_linear_train(W, H, args, device="cpu"):
    
    sigma_reg = getattr(args, "sigma_reg", 1e-2)
    if H is not None:
        n_h = H.shape[0]
        H = utils.regularize_H2(H.clone(), n_h, sigma_reg)
    
    target_dtype = torch.float32
    target = W.to(device=device, dtype=target_dtype)
    out_features, in_features = target.shape

    target, Hr, metadata = utils.standardize_W(target, H, args, device, None)

    epochs = int(getattr(args, "ecft_epochs", 0) or 0)
    lmbda = float(getattr(args, "ecft_lmbda", 0.0) or 0.0)
    decoder_type = _resolve_decoder_type(args)
    rht_seed = _resolve_rht_seed(args)
    quantize_mode = str(getattr(args, "ecft_mode", "noise"))
    if quantize_mode not in ("noise", "ste"):
        raise ValueError(
            f"--ecft_mode must be 'noise' or 'ste', got {quantize_mode!r}"
        )

    layer = _build_ec_layer(
        args,
        in_features=in_features,
        out_features=out_features,
        decoder_type=decoder_type,
        rht_seed=rht_seed,
        device=target.device,
        dtype=target.dtype,
    )
    layer.quantize_mode = quantize_mode
    encode_target = target

    layer.initialize_from_weight(encode_target)

    # Load pretrained Gaussian priors if path is set — this overwrites the
    # freshly-initialized qs / entropy_bottleneck / (B for lattice) with the
    # pre-learned values.
    applied_pretrained = _maybe_apply_pretrained(layer, args)

    history: list[dict[str, Any]] = []
    log_path = _ecft_log_path(args)
    _ecft_log_init(log_path, epochs=epochs, lmbda=lmbda, decoder_type=decoder_type)
    if applied_pretrained:
        # Use pretrained qs as-is; skip the per-latent binary search.
        qs = layer.qs
        glog.info(f"[ec pretrained] skip qs search, using pretrained qs={float(qs):.4f}")
    else:
        qs = _search_qs_for_target_rate(
            layer,
            args,
            device=target.device,
            dtype=target.dtype,
            log_path=log_path,
        )
        layer.qs = qs

    opt_args = _build_optimizer_args(args)
    optimizer, aux_optimizer = configure_ec_optimizers(layer, opt_args)

    warmup_steps = int(getattr(args, "ecft_aux_warmup_step", 0) or 0)
    warmup_rate_last = float("nan")
    warmup_aux_last = float("nan")
    if warmup_steps > 0:
        layer.train()
        log_every = max(1, warmup_steps // 5)
        # log_every = 1
        latent_requires_grad = layer.latent.requires_grad
        left_diag_requires_grad = layer.left_diag.requires_grad
        right_diag_requires_grad = layer.right_diag.requires_grad
        try:
            layer.latent.requires_grad_(False)
            layer.left_diag.requires_grad_(False)
            layer.right_diag.requires_grad_(False)
            with torch.enable_grad():
                for step in range(warmup_steps):
                    optimizer.zero_grad(set_to_none=True)
                    if aux_optimizer is not None:
                        aux_optimizer.zero_grad(set_to_none=True)

                    layer.quantize_latent(training=False, return_likelihoods=False)
                    rate_loss = layer._last_rate_loss
                    (10*rate_loss).backward()

                    aux_loss_value = torch.tensor(0.0, device=target.device)
                    if aux_optimizer is not None:
                        aux_loss_value = layer.aux_loss()
                        aux_loss_value.backward()

                    optimizer.step()
                    if aux_optimizer is not None:
                        aux_optimizer.step()

                    warmup_rate_last = float(rate_loss.item())
                    warmup_aux_last = float(aux_loss_value.item())
                    row = {
                        "stage": "warmup",
                        "epoch": 0.0,
                        "loss": warmup_rate_last,
                        "mse_loss": float("nan"),
                        "rate_loss": warmup_rate_last,
                        "aux_loss": warmup_aux_last,
                    }
                    history.append(row)
                    _ecft_log_append_train(log_path, row)

                    if bool(getattr(args, "verbose", False)) and (
                        ((step + 1) % log_every == 0) or (step == 0) or (step + 1 == warmup_steps)
                    ):
                        glog.info(
                            f"{args.layer_idx}_{args.layer_name} [ECFT warmup] step {step + 1}/{warmup_steps} "
                            f"rate={warmup_rate_last:.6f} aux={warmup_aux_last:.6f}"
                        )
        finally:
            layer.latent.requires_grad_(latent_requires_grad)
            layer.left_diag.requires_grad_(left_diag_requires_grad)
            layer.right_diag.requires_grad_(right_diag_requires_grad)

        layer.update_entropy_model(force=True, update_quantiles=True)

    best_state = _clone_best_state(layer)
    best_loss = math.inf

    target_rate_value = getattr(args, "R_target", None)
    use_adaptive_lambda = bool(getattr(args, "ecft_adaptive_lambda", False))
    if use_adaptive_lambda:
        if target_rate_value is None:
            raise ValueError(
                "ecft_adaptive_lambda=True requires --R_target to set target rate."
            )
        target_rate_value = float(target_rate_value)
        lambda_rate = float(lmbda)
        lambda_rate_lr = float(getattr(args, "ecft_lambda_lr", 0.1))
        lambda_rate_min = float(getattr(args, "ecft_lambda_min", 0.0))
        lambda_rate_max = float(getattr(args, "ecft_lambda_max", 1e8))
        rate_ema_beta = float(getattr(args, "ecft_rate_ema_beta", 0.9))
        rate_tolerance = float(getattr(args, "ecft_rate_tolerance", 0.0))
        rate_ema: Optional[float] = None
    else:
        lambda_rate = float(lmbda)
        lambda_rate_lr = 0.0
        lambda_rate_min = 0.0
        lambda_rate_max = 0.0
        rate_ema_beta = 0.0
        rate_tolerance = 0.0
        rate_ema = None

    if epochs > 0:
        layer.train()
        log_every = max(1, epochs // 5)
        with torch.enable_grad():
            for epoch in range(epochs):
                optimizer.zero_grad(set_to_none=True)
                recon, _ = layer.reconstruct_weight(training=True, quantized=True)
                mse_loss = torch.mean((recon - target) ** 2)
                rate_loss = layer._last_rate_loss
                if use_adaptive_lambda:
                    total_loss = mse_loss + lambda_rate * (rate_loss - target_rate_value)
                else:
                    total_loss = mse_loss + lmbda * rate_loss
                # Lattice orthogonality regularizer (ec_linear_lattice_eb only)
                lambda_ortho = float(getattr(layer, "lambda_ortho", 0.0) or 0.0)
                if lambda_ortho > 0.0 and hasattr(layer, "orthogonality_loss"):
                    total_loss = total_loss + lambda_ortho * layer.orthogonality_loss()
                total_loss.backward()
                optimizer.step()

                aux_loss_value = torch.tensor(0.0, device=target.device)
                if aux_optimizer is not None:
                    aux_optimizer.zero_grad(set_to_none=True)
                    aux_loss_value = layer.aux_loss()
                    aux_loss_value.backward()
                    aux_optimizer.step()

                if use_adaptive_lambda:
                    rate_now = float(rate_loss.item())
                    if rate_ema is None:
                        rate_ema = rate_now
                    else:
                        rate_ema = rate_ema_beta * rate_ema + (1.0 - rate_ema_beta) * rate_now
                    rate_error = rate_ema - target_rate_value
                    if abs(rate_error) < rate_tolerance:
                        rate_error = 0.0
                    lambda_rate = float(
                        max(
                            lambda_rate_min,
                            min(lambda_rate_max, lambda_rate + lambda_rate_lr * rate_error),
                        )
                    )

                loss_value = float(total_loss.item())
                if loss_value < best_loss:
                    best_loss = loss_value
                    best_state = _clone_best_state(layer)

                row = {
                    "stage": "train",
                    "epoch": float(epoch + 1),
                    "loss": loss_value,
                    "mse_loss": float(mse_loss.item()),
                    "rate_loss": float(rate_loss.item()),
                    "aux_loss": float(aux_loss_value.item()),
                    "lambda_rate": float(lambda_rate),
                }
                history.append(row)
                _ecft_log_append_train(log_path, row)
                if bool(getattr(args, "verbose", False)) and (
                    ((epoch + 1) % log_every == 0) or (epoch == 0) or (epoch + 1 == epochs)
                ):
                    if use_adaptive_lambda:
                        glog.info(
                            f"{args.layer_idx}_{args.layer_name} [ECFT] epoch {epoch + 1}/{epochs} "
                            f"loss={row['loss']:.6f} mse={row['mse_loss']:.6f} "
                            f"rate={row['rate_loss']:.6f} aux={row['aux_loss']:.6f} "
                            f"target={target_rate_value:.6f} lambda={lambda_rate:.6f}"
                        )
                    else:
                        glog.info(
                            f"{args.layer_idx}_{args.layer_name} [ECFT] epoch {epoch + 1}/{epochs} "
                            f"loss={row['loss']:.6f} mse={row['mse_loss']:.6f} "
                            f"rate={row['rate_loss']:.6f} aux={row['aux_loss']:.6f}"
                        )

    layer.load_state_dict(best_state, strict=True)
    layer.eval()

    with torch.no_grad():
        quantized_latent, _ = layer.quantize_latent(training=False, return_likelihoods=False)
        hat_wr = layer.decode_latent(quantized_latent)
        mse_loss = torch.mean((hat_wr - target) ** 2)
        rate_loss = layer._last_rate_loss
        est_total_bits = float(rate_loss.item() * target.numel())

        compressed = layer.compress_latent(force_update=True, update_quantiles=False)
        real_total_bits = int(compressed["num_bits"])
        num_pixels = int(target.numel())

    decoder_bits = layer.decoding_parameter_bit_breakdown(
        include_entropy_medians=True,
        force_update_entropy_tables=False,
    )
    _ecft_log_append_final(
        log_path,
        mse_loss=float(mse_loss.item()),
        rate_loss=float(rate_loss.item()),
        bpp=float(real_total_bits / num_pixels),
        decoder_bits_total=int(decoder_bits.get("total", 0)),
    )

    ecsq_compare = {
        "ran": False,
        "reason": "H is None",
    }
    # if H is not None:
    #     target_rate = float(rate_loss.item())
    #     ecsq_args = copy.deepcopy(args)
    #     setattr(ecsq_args, "R_target", target_rate)
    #     try:
    #         ecsq_out = ecsq.uniform_ecsq_gpu(W.clone(), H.clone(), ecsq_args, device=device)
    #         ecsq_hat_wr = ecsq_out["hatWr"].to(device=target.device, dtype=target_dtype)
    #         ecsq_w_hat = utils.de_standardize_Wr(ecsq_hat_wr, ecsq_out["metadata"], ecsq_args, None)
    #         if ecsq_w_hat.device != target.device:
    #             ecsq_w_hat = ecsq_w_hat.to(target.device)

    #         ecsq_mse = float(torch.mean((ecsq_w_hat - target) ** 2).item())
    #         ecsq_rate = float(ecsq_out["bpp_loss"])
    #         ec_mse = float(mse_loss.item())
    #         ec_rate = float(rate_loss.item())
    #         ecsq_compare = {
    #             "ran": True,
    #             "target_rate_from_ec": target_rate,
    #             "ec": {
    #                 "mse": ec_mse,
    #                 "rate_loss": ec_rate,
    #             },
    #             "ecsq": {
    #                 "mse": ecsq_mse,
    #                 "rate": ecsq_rate,
    #                 "rate_target_theory": float(ecsq_out.get("bpp_target", float("nan"))),
    #                 "bpp_sum": float(ecsq_out["bpp_sum"]),
    #             },
    #             "delta": {
    #                 "mse_ec_minus_ecsq": ec_mse - ecsq_mse,
    #                 "rate_ec_minus_ecsq": ec_rate - ecsq_rate,
    #             },
    #         }
    #         glog.info(
    #             "[EC vs ECSQ] "
    #             f"target_rate={target_rate:.6f} "
    #             f"ec(mse={ec_mse:.6f}, rate={ec_rate:.6f}) "
    #             f"ecsq(mse={ecsq_mse:.6f}, rate={ecsq_rate:.6f})"
    #         )
    #     except Exception as exc:
    #         ecsq_compare = {
    #             "ran": False,
    #             "reason": f"ECSQ compare failed: {exc}",
    #         }
    #         glog.warning(ecsq_compare["reason"])
    _ecft_log_append_ecsq_compare(log_path, ecsq_compare)

    fused_layer = copy.deepcopy(layer)
    fused_metadata = _fuse_metadata_into_layer(fused_layer, metadata, args)
    fused_layer = fused_layer.cpu()

    out = {
        "hatWr": hat_wr.to(dtype=W.dtype),
        "bpp_loss_sum": est_total_bits,
        "bpp_loss": float(rate_loss.item()),
        "bpp_sum": real_total_bits,
        "bpp": float(real_total_bits / num_pixels),
        "num_pixels": num_pixels,
        "mse_normed": float(mse_loss.item()),
        # "codes": compressed["strings"],
        "codes": None,
        "metadata": metadata,
        "ec_shape": compressed["shape"],
        "decoder_bits": decoder_bits,
        "ecsq_compare": ecsq_compare,
        "warmup_steps": warmup_steps,
        "warmup_rate_last": warmup_rate_last,
        "warmup_aux_last": warmup_aux_last,
        "adaptive_lambda": use_adaptive_lambda,
        "lambda_rate_final": float(lambda_rate),
        "metadata_fused": fused_metadata,
        "layer": fused_layer,
        "history": history,
    }
    return out
