CUDA_VISIBLE_DEVICES=2 taskset -c 16-23 python -u train.py --dist_port 6044 \
    --dataset_path ../Wparam_dataset/dataset_per_row/meta-llama/Meta-Llama-3-8B/mlp_attn_16_row_dataset.pt \
    --architecture vqvae \
    --save_dir vqvae \
    --input_size 16 \
    --dim_embeddings 16 \
    --K 8 \
    --P 8 \
    --dim_encoder 512 \
    --batch_size 2048 \
    --loss enmse
